use anyhow::{anyhow, Context, Result};
use chrono::Utc;
use clap::{Args, Parser, Subcommand, ValueEnum};
use globset::{Glob, GlobSet, GlobSetBuilder};
use regex::Regex;
use reqwest::blocking::Client;
use reqwest::Url;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::io::{self, IsTerminal, Write};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Instant;
use walkdir::{DirEntry, WalkDir};

const MAX_TEXT_FILE_BYTES: u64 = 5 * 1024 * 1024;
const MAX_RECORDED_LIMITATION_ITEMS: usize = 100;
const BUNDLED_SKILL_MD: &str = include_str!("../bundled/pypi-supply-chain-response/SKILL.md");
const BUNDLED_IOC_PATTERNS_MD: &str = include_str!("../bundled/pypi-supply-chain-response/references/ioc-patterns.md");

#[derive(Parser, Debug)]
#[command(name = "scira")]
#[command(about = "Host-side incident response agent for PyPI supply chain attacks")]
#[command(version)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Scan a target path or broad host-visible paths for a bundled incident profile.
    Scan(ScanArgs),
    /// Explain a saved JSON report using an LLM.
    Explain(ExplainArgs),
}

#[derive(Args, Debug)]
struct ScanArgs {
    /// Bundled incident identifier. First cut supports: litellm
    incident: String,

    /// Scan this target path. Defaults to the current directory.
    #[arg(long, value_name = "PATH", conflicts_with = "all_dirs")]
    target: Option<PathBuf>,

    /// Broad scan using current user privileges.
    #[arg(long)]
    all_dirs: bool,

    #[arg(long, default_value = "text")]
    format: OutputFormat,

    /// Write the rendered report to a file.
    #[arg(long, value_name = "PATH")]
    output: Option<PathBuf>,

    /// Run AI explanation immediately after the scan.
    #[arg(long)]
    explain: bool,

    /// Never prompt for or run AI explanation.
    #[arg(long)]
    no_explain: bool,

    /// Disable interactive prompts.
    #[arg(long)]
    non_interactive: bool,

    /// Show more finding details in text output.
    #[arg(long)]
    verbose: bool,
}

#[derive(Args, Debug)]
struct ExplainArgs {
    /// Path to a JSON report generated by `scira scan --format json`.
    report: PathBuf,

    #[arg(long, default_value = "text")]
    format: OutputFormat,

    /// Write the explanation to a file.
    #[arg(long, value_name = "PATH")]
    output: Option<PathBuf>,

    /// Override the incident profile if needed. Normally inferred from the report.
    #[arg(long)]
    incident: Option<String>,
}

#[derive(Copy, Clone, Debug, Serialize, Deserialize, ValueEnum, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
enum OutputFormat {
    Text,
    Json,
}

#[derive(Debug, Clone)]
struct IncidentProfile {
    id: &'static str,
    title: &'static str,
    ecosystem: &'static str,
    package: &'static str,
    bad_versions: &'static [&'static str],
    safe_version: &'static str,
    ioc_domains: &'static [&'static str],
    ioc_files: &'static [&'static str],
    search_patterns: &'static [&'static str],
    immediate_next_steps: &'static [&'static str],
    credential_rotation_scope: &'static [&'static str],
    cleanup_and_rebuild: &'static [&'static str],
    source_repo: &'static str,
    source_skill: &'static str,
    source_version: &'static str,
}

#[derive(Debug, Serialize, Deserialize)]
struct ScanReport {
    schema_version: String,
    incident: IncidentMetadata,
    scan: ScanMetadata,
    summary: Summary,
    findings: Findings,
    actions: Actions,
    limitations: Limitations,
}

#[derive(Debug, Serialize, Deserialize)]
struct IncidentMetadata {
    id: String,
    title: String,
    ecosystem: String,
    package: String,
    bad_versions: Vec<String>,
    safe_version: String,
    ioc_domains: Vec<String>,
    ioc_files: Vec<String>,
    source: IncidentSource,
}

#[derive(Debug, Serialize, Deserialize)]
struct IncidentSource {
    repo: String,
    skill: String,
    version: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct ScanMetadata {
    target: String,
    mode: String,
    hostname: String,
    user: String,
    started_at: String,
    completed_at: String,
    duration_ms: u128,
    interactive: bool,
    llm_available: bool,
}

#[derive(Debug, Serialize, Deserialize)]
struct Summary {
    status: IncidentStatus,
    reason: String,
    confidence_notes: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct Findings {
    manifest_hits: Vec<ManifestHit>,
    version_hits: Vec<VersionHit>,
    ioc_file_hits: Vec<IocHit>,
    ioc_domain_hits: Vec<IocHit>,
    environment_hits: Vec<EnvironmentFinding>,
    cache_hits: Vec<CacheHit>,
    skipped_checks: Vec<SkippedCheck>,
}

#[derive(Debug, Serialize, Deserialize)]
struct ManifestHit {
    path: String,
    line_number: usize,
    line: String,
    pinned_version: Option<String>,
    match_kind: ManifestMatchKind,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum ManifestMatchKind {
    LooseReference,
    PinnedReference,
}

#[derive(Debug, Serialize, Deserialize)]
struct VersionHit {
    path: String,
    line_number: usize,
    line: String,
    version: String,
    status: VersionHitStatus,
}

#[derive(Debug, Copy, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
enum VersionHitStatus {
    Compromised,
    Safe,
    Other,
}

#[derive(Debug, Serialize, Deserialize)]
struct IocHit {
    indicator: String,
    path: String,
    line_number: Option<usize>,
    line: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct EnvironmentFinding {
    check: String,
    status: String,
    details: String,
    version: Option<String>,
    bad_version: bool,
    raw: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct CacheHit {
    source: String,
    path: String,
    details: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct SkippedCheck {
    check: String,
    reason: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct Actions {
    immediate_next_steps: Vec<String>,
    credential_rotation_scope: Vec<String>,
    cleanup_and_rebuild: Vec<String>,
    manual_verification_steps: Vec<String>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct Limitations {
    permission_denied_paths: Vec<String>,
    missing_tools: Vec<String>,
    not_inspected: Vec<String>,
    notes: Vec<String>,
}

#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
enum IncidentStatus {
    NoIndicatorsFound,
    ReferencesFoundFollowUpNeeded,
    LikelyAffected,
}

#[derive(Debug, Clone)]
struct LlmConfig {
    provider: LlmProvider,
    api_key: String,
    model: String,
    base_url: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "snake_case")]
enum LlmProvider {
    Anthropic,
    Openai,
    Gemini,
}

#[derive(Debug, Serialize)]
struct ExplainOutput {
    provider: String,
    model: String,
    explanation: String,
}

#[derive(Debug, Default)]
struct PythonEnvScan {
    findings: Vec<EnvironmentFinding>,
    cache_hits: Vec<CacheHit>,
    ioc_file_hits: Vec<IocHit>,
    skipped_checks: Vec<SkippedCheck>,
}

fn main() {
    let exit_code = match real_main() {
        Ok(code) => code,
        Err(err) => {
            eprintln!("error: {err}");
            1
        }
    };
    std::process::exit(exit_code);
}

fn real_main() -> Result<i32> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Scan(args) => run_scan_command(args),
        Commands::Explain(args) => run_explain_command(args),
    }
}

fn run_scan_command(args: ScanArgs) -> Result<i32> {
    let profile = incident_profile(&args.incident)?;
    let interactive = !args.non_interactive && io::stdin().is_terminal() && io::stdout().is_terminal();
    let llm_config = detect_llm_config()?;

    let target = if args.all_dirs {
        PathBuf::from("/")
    } else {
        match args.target {
            Some(path) => expand_tilde(path),
            None => env::current_dir().context("failed to determine current directory")?,
        }
    };

    if !args.all_dirs {
        ensure_target_is_accessible(&target)?;
    }

    let report = perform_scan(&profile, &target, args.all_dirs, interactive, llm_config.is_some())?;
    let rendered = match args.format {
        OutputFormat::Json => serde_json::to_string_pretty(&report)?,
        OutputFormat::Text => render_scan_report_text(&report, args.verbose),
    };

    emit_output(&rendered, args.output.as_ref())?;

    if args.explain {
        let config = llm_config.ok_or_else(missing_llm_config_error)?;
        let output = explain_report(&profile, &report, &config)?;
        println!("\n{}", render_explain_text(&output));
    } else if !args.no_explain && args.format == OutputFormat::Text && interactive {
        if let Some(config) = llm_config {
            if prompt_yes_no("\nScan complete. Would you like an AI explanation and remediation summary? [Y/n] ", true)? {
                let output = explain_report(&profile, &report, &config)?;
                println!("\n{}", render_explain_text(&output));
            }
        } else {
            println!(
                "\nTip: AI explanation is not available because no LLM API key was found.\nSet SCIRA_LLM_API_KEY to enable explanation. scira will try to detect the provider and choose a default model automatically.\nIf auto-detection does not work, also set SCIRA_LLM_PROVIDER."
            );
        }
    }

    Ok(exit_code_for_status(report.summary.status))
}

fn run_explain_command(args: ExplainArgs) -> Result<i32> {
    let report_raw = fs::read_to_string(&args.report)
        .with_context(|| format!("failed reading report file {}", args.report.display()))?;
    let report: ScanReport = serde_json::from_str(&report_raw)
        .with_context(|| format!("failed parsing JSON report {}", args.report.display()))?;

    let incident_id = args.incident.unwrap_or_else(|| report.incident.id.clone());
    let profile = incident_profile(&incident_id)?;
    let config = detect_llm_config()?.ok_or_else(missing_llm_config_error)?;
    let output = explain_report(&profile, &report, &config)?;

    let rendered = match args.format {
        OutputFormat::Json => serde_json::to_string_pretty(&output)?,
        OutputFormat::Text => render_explain_text(&output),
    };
    emit_output(&rendered, args.output.as_ref())?;

    Ok(0)
}

fn perform_scan(
    profile: &IncidentProfile,
    target: &Path,
    all_dirs: bool,
    interactive: bool,
    llm_available: bool,
) -> Result<ScanReport> {
    let started_at = Utc::now();
    let timer = Instant::now();

    let mut limitations = Limitations::default();
    let mut findings = Findings {
        manifest_hits: Vec::new(),
        version_hits: Vec::new(),
        ioc_file_hits: Vec::new(),
        ioc_domain_hits: Vec::new(),
        environment_hits: Vec::new(),
        cache_hits: Vec::new(),
        skipped_checks: Vec::new(),
    };

    let matcher = build_matcher(profile.search_patterns)?;
    let candidate_files = collect_candidate_files(target, &matcher, &mut limitations)?;
    scan_candidate_files(profile, target, &candidate_files, &mut findings, &mut limitations)?;

    let python_scan = scan_python_environment(profile, &mut limitations)?;
    findings.environment_hits.extend(python_scan.findings);
    findings.cache_hits.extend(python_scan.cache_hits);
    findings.ioc_file_hits.extend(python_scan.ioc_file_hits);
    findings.skipped_checks.extend(python_scan.skipped_checks);

    let summary = build_summary(&findings, &limitations);
    let actions = build_actions(profile, &summary, &limitations);
    let completed_at = Utc::now();

    Ok(ScanReport {
        schema_version: "1".to_string(),
        incident: IncidentMetadata {
            id: profile.id.to_string(),
            title: profile.title.to_string(),
            ecosystem: profile.ecosystem.to_string(),
            package: profile.package.to_string(),
            bad_versions: profile.bad_versions.iter().map(|s| s.to_string()).collect(),
            safe_version: profile.safe_version.to_string(),
            ioc_domains: profile.ioc_domains.iter().map(|s| s.to_string()).collect(),
            ioc_files: profile.ioc_files.iter().map(|s| s.to_string()).collect(),
            source: IncidentSource {
                repo: profile.source_repo.to_string(),
                skill: profile.source_skill.to_string(),
                version: profile.source_version.to_string(),
            },
        },
        scan: ScanMetadata {
            target: target.display().to_string(),
            mode: if all_dirs {
                "all_dirs".to_string()
            } else if target == env::current_dir().unwrap_or_else(|_| PathBuf::from(".")) {
                "default_target".to_string()
            } else {
                "explicit_target".to_string()
            },
            hostname: detect_hostname(),
            user: detect_user(),
            started_at: started_at.to_rfc3339(),
            completed_at: completed_at.to_rfc3339(),
            duration_ms: timer.elapsed().as_millis(),
            interactive,
            llm_available,
        },
        summary,
        findings,
        actions,
        limitations,
    })
}

fn scan_candidate_files(
    profile: &IncidentProfile,
    target_root: &Path,
    candidate_files: &[PathBuf],
    findings: &mut Findings,
    limitations: &mut Limitations,
) -> Result<()> {
    let package_re = Regex::new(&format!(r"(?i)\b{}\b", regex::escape(profile.package)))?;
    let exact_pin_re = Regex::new(&format!(
        r"(?i)\b{}\b(?:\[[^\]]+\])?\s*==\s*([A-Za-z0-9._+-]+)",
        regex::escape(profile.package)
    ))?;

    for file in candidate_files {
        let content = match fs::read(file) {
            Ok(bytes) => String::from_utf8_lossy(&bytes).to_string(),
            Err(err) if err.kind() == io::ErrorKind::PermissionDenied => {
                push_limited(
                    &mut limitations.permission_denied_paths,
                    file.display().to_string(),
                );
                continue;
            }
            Err(err) => {
                push_limited(
                    &mut limitations.not_inspected,
                    format!("{} ({err})", file.display()),
                );
                continue;
            }
        };

        for (idx, line) in content.lines().enumerate() {
            if package_re.is_match(line) {
                let pinned_version = exact_pin_re
                    .captures(line)
                    .and_then(|caps| caps.get(1).map(|m| m.as_str().to_string()));

                findings.manifest_hits.push(ManifestHit {
                    path: file.display().to_string(),
                    line_number: idx + 1,
                    line: line.trim().to_string(),
                    pinned_version: pinned_version.clone(),
                    match_kind: if pinned_version.is_some() {
                        ManifestMatchKind::PinnedReference
                    } else {
                        ManifestMatchKind::LooseReference
                    },
                });

                if let Some(version) = pinned_version {
                    findings.version_hits.push(VersionHit {
                        path: file.display().to_string(),
                        line_number: idx + 1,
                        line: line.trim().to_string(),
                        status: classify_version(profile, &version),
                        version,
                    });
                }
            }

            for domain in profile.ioc_domains {
                if line.contains(domain) {
                    findings.ioc_domain_hits.push(IocHit {
                        indicator: domain.to_string(),
                        path: file.display().to_string(),
                        line_number: Some(idx + 1),
                        line: Some(line.trim().to_string()),
                    });
                }
            }
        }
    }

    findings.ioc_file_hits.extend(search_ioc_files(
        &[target_root.to_path_buf()],
        profile.ioc_files,
        limitations,
        false,
    )?);

    Ok(())
}

fn scan_python_environment(profile: &IncidentProfile, limitations: &mut Limitations) -> Result<PythonEnvScan> {
    let mut result = PythonEnvScan::default();
    let python = detect_python();

    let Some(python) = python else {
        push_limited(&mut limitations.missing_tools, "python".to_string());
        result.skipped_checks.push(SkippedCheck {
            check: "python_environment".to_string(),
            reason: "python or python3 was not found".to_string(),
        });
        return Ok(result);
    };

    let pip_show = run_command_capture(&python, &["-m", "pip", "show", profile.package]);
    match pip_show {
        Ok(output) if output.status.success() && !output.stdout.trim().is_empty() => {
            let version = parse_pip_show_field(&output.stdout, "Version");
            let location = parse_pip_show_field(&output.stdout, "Location").unwrap_or_else(|| "unknown".to_string());
            result.findings.push(EnvironmentFinding {
                check: "pip_show".to_string(),
                status: "present".to_string(),
                details: format!("Installed package found via pip show at {location}"),
                bad_version: version
                    .as_ref()
                    .map(|v| profile.bad_versions.iter().any(|bad| *bad == v.as_str()))
                    .unwrap_or(false),
                version,
                raw: Some(output.stdout),
            });
        }
        Ok(output) if output.status.success() => {
            result.findings.push(EnvironmentFinding {
                check: "pip_show".to_string(),
                status: "not_present".to_string(),
                details: "Package not found via pip show".to_string(),
                version: None,
                bad_version: false,
                raw: None,
            });
        }
        Ok(output) => {
            result.findings.push(EnvironmentFinding {
                check: "pip_show".to_string(),
                status: "not_present".to_string(),
                details: "Package not found via pip show".to_string(),
                version: None,
                bad_version: false,
                raw: if output.stderr.trim().is_empty() { None } else { Some(output.stderr) },
            });
        }
        Err(err) => {
            if err.kind() == io::ErrorKind::NotFound {
                push_limited(&mut limitations.missing_tools, "pip".to_string());
            }
            result.skipped_checks.push(SkippedCheck {
                check: "pip_show".to_string(),
                reason: err.to_string(),
            });
        }
    }

    match run_command_capture(&python, &["-m", "pip", "freeze"]) {
        Ok(output) if output.status.success() => {
            let mut matched = false;
            for line in output.stdout.lines() {
                if line.to_lowercase().starts_with(&format!("{}==", profile.package.to_lowercase())) {
                    matched = true;
                    let version = line.split("==").nth(1).map(|s| s.trim().to_string());
                    result.findings.push(EnvironmentFinding {
                        check: "pip_freeze".to_string(),
                        status: "present".to_string(),
                        details: format!("Package appears in pip freeze: {}", line.trim()),
                        bad_version: version
                            .as_ref()
                            .map(|v| profile.bad_versions.iter().any(|bad| *bad == v.as_str()))
                            .unwrap_or(false),
                        version,
                        raw: Some(line.trim().to_string()),
                    });
                }
            }
            if !matched {
                result.findings.push(EnvironmentFinding {
                    check: "pip_freeze".to_string(),
                    status: "not_present".to_string(),
                    details: "Package not found in pip freeze".to_string(),
                    version: None,
                    bad_version: false,
                    raw: None,
                });
            }
        }
        Ok(output) => result.skipped_checks.push(SkippedCheck {
            check: "pip_freeze".to_string(),
            reason: stderr_or_fallback(&output.stderr, "pip freeze did not succeed"),
        }),
        Err(err) => result.skipped_checks.push(SkippedCheck {
            check: "pip_freeze".to_string(),
            reason: err.to_string(),
        }),
    }

    match run_command_capture(&python, &["-m", "pip", "inspect"]) {
        Ok(output) if output.status.success() => {
            let contains_package = output.stdout.to_lowercase().contains(&format!("\"name\": \"{}\"", profile.package.to_lowercase()));
            result.findings.push(EnvironmentFinding {
                check: "pip_inspect".to_string(),
                status: if contains_package { "present" } else { "completed" }.to_string(),
                details: if contains_package {
                    "Package appears in pip inspect output; review for dependency chain details".to_string()
                } else {
                    "pip inspect completed; package not clearly present in output".to_string()
                },
                version: None,
                bad_version: false,
                raw: None,
            });
        }
        Ok(output) => result.skipped_checks.push(SkippedCheck {
            check: "pip_inspect".to_string(),
            reason: stderr_or_fallback(&output.stderr, "pip inspect is not available"),
        }),
        Err(err) => result.skipped_checks.push(SkippedCheck {
            check: "pip_inspect".to_string(),
            reason: err.to_string(),
        }),
    }

    match run_command_capture("pipdeptree", &["-r", "-p", profile.package]) {
        Ok(output) if output.status.success() && !output.stdout.trim().is_empty() => {
            result.findings.push(EnvironmentFinding {
                check: "pipdeptree".to_string(),
                status: "present".to_string(),
                details: "Reverse dependency chain found via pipdeptree".to_string(),
                version: None,
                bad_version: false,
                raw: Some(output.stdout),
            });
        }
        Ok(_) => result.findings.push(EnvironmentFinding {
            check: "pipdeptree".to_string(),
            status: "not_present".to_string(),
            details: "No reverse dependency chain found via pipdeptree".to_string(),
            version: None,
            bad_version: false,
            raw: None,
        }),
        Err(err) => {
            if err.kind() == io::ErrorKind::NotFound {
                push_limited(&mut limitations.missing_tools, "pipdeptree".to_string());
            }
            result.skipped_checks.push(SkippedCheck {
                check: "pipdeptree".to_string(),
                reason: err.to_string(),
            });
        }
    }

    let mut env_paths = Vec::new();
    if let Some(home) = home_dir() {
        env_paths.push(home.join(".cache/pip"));
        env_paths.push(home.join(".cache/uv"));
    }

    if let Ok(output) = run_command_capture(
        &python,
        &["-c", "import json, site; paths=[]; user=site.getusersitepackages();\nif user: paths.append(user)\nfor p in getattr(site, 'getsitepackages', lambda: [])():\n    if p not in paths: paths.append(p)\nprint(json.dumps(paths))"],
    ) {
        if output.status.success() {
            if let Ok(paths) = serde_json::from_str::<Vec<String>>(&output.stdout) {
                for p in paths {
                    env_paths.push(PathBuf::from(p));
                }
            }
        }
    }

    result.cache_hits.extend(scan_cache_hits(profile.package, &env_paths, limitations)?);
    result.ioc_file_hits.extend(search_ioc_files(&env_paths, profile.ioc_files, limitations, true)?);

    Ok(result)
}

fn build_summary(findings: &Findings, limitations: &Limitations) -> Summary {
    let likely_affected = findings
        .version_hits
        .iter()
        .any(|hit| matches!(hit.status, VersionHitStatus::Compromised))
        || findings.environment_hits.iter().any(|f| f.bad_version)
        || !findings.ioc_file_hits.is_empty()
        || !findings.ioc_domain_hits.is_empty();

    let references_found = !findings.manifest_hits.is_empty()
        || findings.environment_hits.iter().any(|f| f.status == "present")
        || !findings.cache_hits.is_empty();

    let status = if likely_affected {
        IncidentStatus::LikelyAffected
    } else if references_found {
        IncidentStatus::ReferencesFoundFollowUpNeeded
    } else {
        IncidentStatus::NoIndicatorsFound
    };

    let reason = match status {
        IncidentStatus::LikelyAffected => {
            if findings
                .version_hits
                .iter()
                .any(|hit| matches!(hit.status, VersionHitStatus::Compromised))
                || findings.environment_hits.iter().any(|f| f.bad_version)
            {
                "A compromised version or strong IOC evidence was found during the scan.".to_string()
            } else {
                "IOC evidence was found even though a compromised version was not confirmed in the scanned manifests.".to_string()
            }
        }
        IncidentStatus::ReferencesFoundFollowUpNeeded => {
            "The package or related references were found, but the scan did not confirm a compromised version.".to_string()
        }
        IncidentStatus::NoIndicatorsFound => {
            "No indicators were found in the checks that completed successfully.".to_string()
        }
    };

    let mut confidence_notes = Vec::new();
    if !limitations.permission_denied_paths.is_empty() {
        confidence_notes.push("Some paths could not be inspected with the current user. Results may be incomplete.".to_string());
    }
    if !limitations.missing_tools.is_empty() {
        confidence_notes.push(format!(
            "Some environment checks were skipped because tools were unavailable: {}.",
            limitations.missing_tools.join(", ")
        ));
    }
    if confidence_notes.is_empty() {
        confidence_notes.push("Deterministic findings shown here are the source of truth for this run.".to_string());
    }

    Summary {
        status,
        reason,
        confidence_notes,
    }
}

fn build_actions(profile: &IncidentProfile, summary: &Summary, limitations: &Limitations) -> Actions {
    let mut manual_verification_steps = vec![
        "Review transitive dependency paths, especially if the package is pulled in by frameworks like DSPy, CrewAI, or Browser-Use.".to_string(),
        "Check whether the compromised user or host had access to cloud credentials, SSH keys, Kubernetes configs, or `.env` files.".to_string(),
    ];

    if !limitations.permission_denied_paths.is_empty() {
        manual_verification_steps.push(
            "Some paths could not be inspected. Re-run with sudo if you intend broader host coverage.".to_string(),
        );
    }

    match summary.status {
        IncidentStatus::LikelyAffected => Actions {
            immediate_next_steps: profile
                .immediate_next_steps
                .iter()
                .map(|s| s.to_string())
                .collect(),
            credential_rotation_scope: profile
                .credential_rotation_scope
                .iter()
                .map(|s| s.to_string())
                .collect(),
            cleanup_and_rebuild: profile
                .cleanup_and_rebuild
                .iter()
                .map(|s| s.to_string())
                .collect(),
            manual_verification_steps,
        },
        IncidentStatus::ReferencesFoundFollowUpNeeded => Actions {
            immediate_next_steps: vec![
                "Confirm which top-level package pulled in the dependency, ideally with `pipdeptree -r -p <package>`.".to_string(),
                "Check the installed version in the active environment and compare it to the compromised versions.".to_string(),
                "Inspect user-level caches and site-packages for IOC files or suspicious `.pth` startup hooks.".to_string(),
            ],
            credential_rotation_scope: vec![
                "Rotate credentials if a compromised version is later confirmed or if IOC evidence appears.".to_string(),
            ],
            cleanup_and_rebuild: vec![
                "Pin to the known-safe version before the next install or rebuild.".to_string(),
                "Purge pip and uv caches if a compromised wheel may have been downloaded.".to_string(),
            ],
            manual_verification_steps,
        },
        IncidentStatus::NoIndicatorsFound => Actions {
            immediate_next_steps: vec![
                "No indicators were found in this run. Keep monitoring advisories for updated IOCs or additional compromised versions.".to_string(),
                "Re-run with broader privileges if you intended a full host scan and some paths were skipped.".to_string(),
            ],
            credential_rotation_scope: vec![
                "Credential rotation is not indicated by this report alone, but review skipped paths and environment coverage before concluding the host is clear.".to_string(),
            ],
            cleanup_and_rebuild: vec![
                format!("If you rebuild, pin {}=={} or another known-safe version.", profile.package, profile.safe_version),
            ],
            manual_verification_steps,
        },
    }
}

fn collect_candidate_files(target: &Path, matcher: &GlobSet, limitations: &mut Limitations) -> Result<Vec<PathBuf>> {
    let mut files = Vec::new();

    for entry in WalkDir::new(target)
        .follow_links(false)
        .into_iter()
        .filter_entry(|entry| !should_skip_scan_entry(entry))
    {
        match entry {
            Ok(entry) => {
                if !entry.file_type().is_file() {
                    continue;
                }
                let path = entry.path();
                let rel = path.strip_prefix(target).unwrap_or(path);
                let file_name = path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default();
                let file_name_path = Path::new(&file_name);

                if !(matcher.is_match(rel) || matcher.is_match(file_name_path)) {
                    continue;
                }

                match entry.metadata() {
                    Ok(metadata) if metadata.len() > MAX_TEXT_FILE_BYTES => push_limited(
                        &mut limitations.not_inspected,
                        format!("{} (file larger than {} bytes)", path.display(), MAX_TEXT_FILE_BYTES),
                    ),
                    Ok(_) => files.push(path.to_path_buf()),
                    Err(err) => {
                        let is_permission_denied = err
                            .io_error()
                            .map(|e| e.kind() == io::ErrorKind::PermissionDenied)
                            .unwrap_or(false);
                        if is_permission_denied {
                            push_limited(&mut limitations.permission_denied_paths, path.display().to_string())
                        } else {
                            push_limited(
                                &mut limitations.not_inspected,
                                format!("{} ({err})", path.display()),
                            )
                        }
                    }
                }
            }
            Err(err) => {
                let path = err
                    .path()
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|| "unknown path".to_string());
                push_limited(&mut limitations.permission_denied_paths, path);
            }
        }
    }

    Ok(files)
}

fn scan_cache_hits(package: &str, roots: &[PathBuf], limitations: &mut Limitations) -> Result<Vec<CacheHit>> {
    let mut hits = Vec::new();
    let needle = package.to_lowercase();

    for root in dedupe_paths(roots) {
        if !root.exists() {
            continue;
        }
        for entry in WalkDir::new(&root)
            .follow_links(false)
            .into_iter()
            .filter_entry(|entry| !should_skip_scan_entry(entry))
        {
            match entry {
                Ok(entry) => {
                    let name = entry.file_name().to_string_lossy().to_lowercase();
                    if name.contains(&needle) {
                        hits.push(CacheHit {
                            source: classify_cache_source(&root),
                            path: entry.path().display().to_string(),
                            details: format!("Package-related cache artifact found under {}", root.display()),
                        });
                        if hits.len() >= 50 {
                            return Ok(hits);
                        }
                    }
                }
                Err(err) => {
                    let path = err
                        .path()
                        .map(|p| p.display().to_string())
                        .unwrap_or_else(|| root.display().to_string());
                    push_limited(&mut limitations.permission_denied_paths, path);
                }
            }
        }
    }

    Ok(hits)
}

fn search_ioc_files(
    roots: &[PathBuf],
    ioc_files: &[&str],
    limitations: &mut Limitations,
    skip_root: bool,
) -> Result<Vec<IocHit>> {
    let ioc_names: BTreeSet<String> = ioc_files.iter().map(|s| s.to_string()).collect();
    let mut hits = Vec::new();

    for root in dedupe_paths(roots) {
        if !root.exists() {
            continue;
        }
        for entry in WalkDir::new(&root)
            .follow_links(false)
            .into_iter()
            .filter_entry(|entry| !should_skip_scan_entry(entry))
        {
            match entry {
                Ok(entry) => {
                    if !entry.file_type().is_file() {
                        continue;
                    }
                    let file_name = entry.file_name().to_string_lossy().to_string();
                    if ioc_names.contains(&file_name) {
                        hits.push(IocHit {
                            indicator: file_name,
                            path: entry.path().display().to_string(),
                            line_number: None,
                            line: None,
                        });
                    }
                }
                Err(err) => {
                    let path = err
                        .path()
                        .map(|p| p.display().to_string())
                        .unwrap_or_else(|| root.display().to_string());
                    if !skip_root || path != root.display().to_string() {
                        push_limited(&mut limitations.permission_denied_paths, path);
                    }
                }
            }
        }
    }

    Ok(hits)
}

fn explain_report(profile: &IncidentProfile, report: &ScanReport, config: &LlmConfig) -> Result<ExplainOutput> {
    let system_prompt = build_explainer_system_prompt();
    let user_prompt = build_explainer_user_prompt(profile, report)?;
    let explanation = match config.provider {
        LlmProvider::Anthropic => call_anthropic(config, &system_prompt, &user_prompt)?,
        LlmProvider::Openai => call_openai(config, &system_prompt, &user_prompt)?,
        LlmProvider::Gemini => call_gemini(config, &system_prompt, &user_prompt)?,
    };

    Ok(ExplainOutput {
        provider: config.provider.as_str().to_string(),
        model: config.model.clone(),
        explanation,
    })
}

fn call_anthropic(config: &LlmConfig, system_prompt: &str, user_prompt: &str) -> Result<String> {
    let client = Client::builder().timeout(std::time::Duration::from_secs(90)).build()?;
    let url = config
        .base_url
        .clone()
        .unwrap_or_else(|| "https://api.anthropic.com/v1/messages".to_string());

    let response: Value = client
        .post(url)
        .header("x-api-key", &config.api_key)
        .header("anthropic-version", "2023-06-01")
        .json(&json!({
            "model": config.model,
            "max_tokens": 1400,
            "system": system_prompt,
            "messages": [
                {"role": "user", "content": user_prompt}
            ]
        }))
        .send()?
        .error_for_status()?
        .json()?;

    let text = response
        .get("content")
        .and_then(|v| v.as_array())
        .and_then(|items| {
            items.iter().find_map(|item| {
                item.get("text")
                    .and_then(|text| text.as_str())
                    .map(|s| s.to_string())
            })
        })
        .ok_or_else(|| anyhow!("anthropic response did not contain text content"))?;

    Ok(text)
}

fn call_openai(config: &LlmConfig, system_prompt: &str, user_prompt: &str) -> Result<String> {
    let client = Client::builder().timeout(std::time::Duration::from_secs(90)).build()?;
    let url = config
        .base_url
        .clone()
        .unwrap_or_else(|| "https://api.openai.com/v1/chat/completions".to_string());

    let response: Value = client
        .post(url)
        .bearer_auth(&config.api_key)
        .json(&json!({
            "model": config.model,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
        }))
        .send()?
        .error_for_status()?
        .json()?;

    let text = response
        .get("choices")
        .and_then(|v| v.as_array())
        .and_then(|choices| choices.first())
        .and_then(|choice| choice.get("message"))
        .and_then(|message| message.get("content"))
        .and_then(|content| content.as_str())
        .map(|s| s.to_string())
        .ok_or_else(|| anyhow!("openai response did not contain message content"))?;

    Ok(text)
}

fn call_gemini(config: &LlmConfig, system_prompt: &str, user_prompt: &str) -> Result<String> {
    let client = Client::builder().timeout(std::time::Duration::from_secs(90)).build()?;
    let base = config
        .base_url
        .clone()
        .unwrap_or_else(|| "https://generativelanguage.googleapis.com/v1beta".to_string());
    let mut url = Url::parse(&format!("{}/models/{}:generateContent", base.trim_end_matches('/'), config.model))?;
    url.query_pairs_mut().append_pair("key", &config.api_key);

    let response: Value = client
        .post(url)
        .json(&json!({
            "system_instruction": {"parts": [{"text": system_prompt}]},
            "contents": [{"parts": [{"text": user_prompt}]}],
            "generationConfig": {"temperature": 0.2}
        }))
        .send()?
        .error_for_status()?
        .json()?;

    let text = response
        .get("candidates")
        .and_then(|v| v.as_array())
        .and_then(|candidates| candidates.first())
        .and_then(|candidate| candidate.get("content"))
        .and_then(|content| content.get("parts"))
        .and_then(|parts| parts.as_array())
        .and_then(|parts| parts.first())
        .and_then(|part| part.get("text"))
        .and_then(|text| text.as_str())
        .map(|s| s.to_string())
        .ok_or_else(|| anyhow!("gemini response did not contain text content"))?;

    Ok(text)
}

fn build_explainer_system_prompt() -> String {
    format!(
        "You are SCIRA, an incident-response agent for Python/PyPI supply chain incidents.\n\
Your job is to explain a deterministic scan report without inventing evidence.\n\
Rules:\n\
- Treat the JSON report as the source of truth.\n\
- Do not claim evidence that is not present in the report.\n\
- Separate observed evidence, likely interpretation, and recommended actions.\n\
- Be explicit when coverage is incomplete due to skipped checks or permission limits.\n\
- Never say the user is definitely safe.\n\
- Remind the user that recommendations are advisory and should be verified before destructive or irreversible actions.\n\
\nBundled skill context:\n\
--- SKILL.md ---\n{}\n\
--- IOC patterns ---\n{}",
        excerpt(BUNDLED_SKILL_MD, 7000),
        excerpt(BUNDLED_IOC_PATTERNS_MD, 5000)
    )
}

fn build_explainer_user_prompt(profile: &IncidentProfile, report: &ScanReport) -> Result<String> {
    let report_json = serde_json::to_string_pretty(report)?;
    Ok(format!(
        "Explain this SCIRA scan report for the bundled incident profile `{}`.\n\
Return these exact sections in order:\n\
1. Executive summary\n\
2. Observed evidence\n\
3. Likely interpretation\n\
4. Priority actions\n\
5. Credential rotation scope\n\
6. Unknowns and what to verify\n\
7. Verification warning\n\
\nIncident profile:\n\
- package: {}\n\
- bad versions: {}\n\
- safe version: {}\n\
- IOC domains: {}\n\
- IOC files: {}\n\
\nDeterministic report JSON:\n{}",
        profile.id,
        profile.package,
        profile.bad_versions.join(", "),
        profile.safe_version,
        profile.ioc_domains.join(", "),
        profile.ioc_files.join(", "),
        report_json
    ))
}

fn detect_llm_config() -> Result<Option<LlmConfig>> {
    let explicit_provider = env::var("SCIRA_LLM_PROVIDER").ok();
    let explicit_model = env::var("SCIRA_LLM_MODEL").ok();
    let explicit_base_url = env::var("SCIRA_LLM_BASE_URL").ok();
    let scira_key = env::var("SCIRA_LLM_API_KEY").ok();

    let provider_and_key = if let Some(provider) = explicit_provider {
        let provider = parse_provider(&provider)?;
        let key = scira_key
            .or_else(|| provider_native_key(provider))
            .ok_or_else(|| anyhow!("SCIRA_LLM_PROVIDER is set but no matching API key was found"))?;
        Some((provider, key))
    } else if let Some(key) = env::var("ANTHROPIC_API_KEY").ok() {
        Some((LlmProvider::Anthropic, key))
    } else if let Some(key) = env::var("OPENAI_API_KEY").ok() {
        Some((LlmProvider::Openai, key))
    } else if let Some(key) = env::var("GEMINI_API_KEY").ok().or_else(|| env::var("GOOGLE_API_KEY").ok()) {
        Some((LlmProvider::Gemini, key))
    } else if let Some(key) = scira_key {
        Some((infer_provider_from_key(&key)?, key))
    } else {
        None
    };

    let Some((provider, api_key)) = provider_and_key else {
        return Ok(None);
    };

    let model = explicit_model.unwrap_or_else(|| default_model(provider).to_string());

    Ok(Some(LlmConfig {
        provider,
        api_key,
        model,
        base_url: explicit_base_url,
    }))
}

fn parse_provider(value: &str) -> Result<LlmProvider> {
    match value.trim().to_lowercase().as_str() {
        "anthropic" => Ok(LlmProvider::Anthropic),
        "openai" | "chatgpt" => Ok(LlmProvider::Openai),
        "gemini" | "google" => Ok(LlmProvider::Gemini),
        other => Err(anyhow!("unsupported provider `{other}`; use anthropic, openai, or gemini")),
    }
}

fn provider_native_key(provider: LlmProvider) -> Option<String> {
    match provider {
        LlmProvider::Anthropic => env::var("ANTHROPIC_API_KEY").ok(),
        LlmProvider::Openai => env::var("OPENAI_API_KEY").ok(),
        LlmProvider::Gemini => env::var("GEMINI_API_KEY").ok().or_else(|| env::var("GOOGLE_API_KEY").ok()),
    }
}

fn infer_provider_from_key(key: &str) -> Result<LlmProvider> {
    if key.starts_with("sk-ant-") {
        Ok(LlmProvider::Anthropic)
    } else if key.starts_with("AIza") {
        Ok(LlmProvider::Gemini)
    } else if key.starts_with("sk-") || key.starts_with("sk-proj-") {
        Ok(LlmProvider::Openai)
    } else {
        Err(anyhow!(
            "SCIRA_LLM_API_KEY was found, but scira could not infer the provider from the key shape. Set SCIRA_LLM_PROVIDER explicitly."
        ))
    }
}

fn default_model(provider: LlmProvider) -> &'static str {
    match provider {
        LlmProvider::Anthropic => "claude-3-5-sonnet-latest",
        LlmProvider::Openai => "gpt-4.1",
        LlmProvider::Gemini => "gemini-2.5-pro",
    }
}

fn incident_profile(id: &str) -> Result<IncidentProfile> {
    match id.trim().to_lowercase().as_str() {
        "litellm" | "litellm-pypi" => Ok(IncidentProfile {
            id: "litellm",
            title: "LiteLLM PyPI compromise",
            ecosystem: "python",
            package: "litellm",
            bad_versions: &["1.82.7", "1.82.8"],
            safe_version: "1.82.6",
            ioc_domains: &["models.litellm.cloud", "checkmarx.zone"],
            ioc_files: &["litellm_init.pth"],
            search_patterns: &[
                "requirements*.txt",
                "requirements-*.txt",
                "pyproject.toml",
                "poetry.lock",
                "uv.lock",
                "Pipfile.lock",
                "setup.py",
                "setup.cfg",
                "Dockerfile",
                "docker-compose*.yml",
                "docker-compose*.yaml",
                "*.log",
            ],
            immediate_next_steps: &[
                "Isolate the affected host, user context, or runner if the compromised version was installed or IOC evidence was found.",
                "Preserve evidence before cleanup where possible: save pip inspect output, freeze output, and relevant logs.",
                "Confirm what pulled the package in, especially if it may be transitive through frameworks like DSPy, CrewAI, or Browser-Use.",
            ],
            credential_rotation_scope: &[
                "Rotate API keys, cloud credentials, SSH keys, Kubernetes configs, Git tokens, and any secrets available to the compromised user or host.",
                "Audit provider logs to see whether rotated credentials were already used maliciously.",
            ],
            cleanup_and_rebuild: &[
                "Uninstall the compromised package and purge pip/uv caches so bad wheels cannot be silently reinstalled.",
                "Remove malicious `.pth` files or other persistence artifacts if found.",
                "Rebuild environments and images from known-good bases, pinning litellm to 1.82.6 or another verified safe version.",
            ],
            source_repo: "https://github.com/makash/agent-infra-security",
            source_skill: "pypi-supply-chain-response",
            source_version: "2026-03-25",
        }),
        other => Err(anyhow!(
            "unsupported incident `{other}`. First cut supports only `litellm`."
        )),
    }
}

fn render_scan_report_text(report: &ScanReport, verbose: bool) -> String {
    let mut out = String::new();
    out.push_str(&format!("Status: {}\n\n", report.summary.status.as_str()));
    out.push_str("Why:\n");
    out.push_str(&format!("- {}\n", report.summary.reason));

    let evidence = key_evidence_lines(report, verbose);
    if !evidence.is_empty() {
        for line in evidence {
            out.push_str(&format!("- {}\n", line));
        }
    }

    out.push_str("\nImmediate next steps:\n");
    for (idx, step) in report.actions.immediate_next_steps.iter().enumerate() {
        out.push_str(&format!("{}. {}\n", idx + 1, step));
    }

    if !report.actions.credential_rotation_scope.is_empty() {
        out.push_str("\nCredential rotation scope:\n");
        for item in &report.actions.credential_rotation_scope {
            out.push_str(&format!("- {}\n", item));
        }
    }

    if !report.limitations.permission_denied_paths.is_empty()
        || !report.limitations.missing_tools.is_empty()
        || !report.limitations.not_inspected.is_empty()
    {
        out.push_str("\nLimitations:\n");
        if !report.limitations.permission_denied_paths.is_empty() {
            out.push_str("- Some locations could not be inspected with the current user. Results may be incomplete.\n");
            if verbose {
                for path in report.limitations.permission_denied_paths.iter().take(10) {
                    out.push_str(&format!("  - denied: {}\n", path));
                }
            }
        }
        if !report.limitations.missing_tools.is_empty() {
            out.push_str(&format!(
                "- Some environment checks were skipped because tools were unavailable: {}\n",
                report.limitations.missing_tools.join(", ")
            ));
        }
        if !report.limitations.not_inspected.is_empty() && verbose {
            for item in report.limitations.not_inspected.iter().take(10) {
                out.push_str(&format!("  - not inspected: {}\n", item));
            }
        }
        out.push_str("- Re-run with sudo if you want broader host coverage.\n");
    }

    out.push_str("\nScan details:\n");
    out.push_str(&format!("- incident: {}\n", report.incident.id));
    out.push_str(&format!("- target: {}\n", report.scan.target));
    out.push_str(&format!("- user: {}\n", report.scan.user));
    out.push_str(&format!("- host: {}\n", report.scan.hostname));

    out
}

fn render_explain_text(output: &ExplainOutput) -> String {
    format!(
        "AI explanation\n\
Provider: {}\n\
Model: {}\n\
\n{}",
        output.provider, output.model, output.explanation
    )
}

fn emit_output(rendered: &str, output: Option<&PathBuf>) -> Result<()> {
    match output {
        Some(path) => {
            fs::write(path, rendered)
                .with_context(|| format!("failed writing output file {}", path.display()))?;
            if io::stdout().is_terminal() {
                eprintln!("saved output to {}", path.display());
            }
        }
        None => {
            println!("{}", rendered);
        }
    }
    Ok(())
}

fn ensure_target_is_accessible(target: &Path) -> Result<()> {
    if !target.exists() {
        return Err(anyhow!("target path does not exist: {}", target.display()));
    }

    if target.is_dir() {
        fs::read_dir(target)
            .with_context(|| {
                format!(
                    "target path exists but cannot be inspected with the current user: {}\n\nRe-run with sudo if you intend to inspect this location.",
                    target.display()
                )
            })?
            .next();
    } else {
        fs::File::open(target).with_context(|| {
            format!(
                "target path exists but cannot be inspected with the current user: {}\n\nRe-run with sudo if you intend to inspect this location.",
                target.display()
            )
        })?;
    }

    Ok(())
}

fn prompt_yes_no(prompt: &str, default_yes: bool) -> Result<bool> {
    print!("{}", prompt);
    io::stdout().flush()?;
    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let trimmed = input.trim().to_lowercase();
    if trimmed.is_empty() {
        return Ok(default_yes);
    }
    Ok(matches!(trimmed.as_str(), "y" | "yes"))
}

fn detect_python() -> Option<String> {
    if command_exists("python") {
        Some("python".to_string())
    } else if command_exists("python3") {
        Some("python3".to_string())
    } else {
        None
    }
}

fn command_exists(command: &str) -> bool {
    Command::new(command)
        .arg("--version")
        .output()
        .map(|_| true)
        .unwrap_or(false)
}

fn run_command_capture(command: &str, args: &[&str]) -> io::Result<CommandOutput> {
    let output = Command::new(command).args(args).output()?;
    Ok(CommandOutput {
        status: output.status,
        stdout: String::from_utf8_lossy(&output.stdout).to_string(),
        stderr: String::from_utf8_lossy(&output.stderr).to_string(),
    })
}

struct CommandOutput {
    status: std::process::ExitStatus,
    stdout: String,
    stderr: String,
}

fn parse_pip_show_field(output: &str, field: &str) -> Option<String> {
    output.lines().find_map(|line| {
        line.strip_prefix(&format!("{field}:"))
            .map(|value| value.trim().to_string())
    })
}

fn detect_hostname() -> String {
    env::var("HOSTNAME")
        .or_else(|_| env::var("COMPUTERNAME"))
        .or_else(|_| {
            run_command_capture("hostname", &[])
                .map(|out| out.stdout.trim().to_string())
                .map_err(|_| env::VarError::NotPresent)
        })
        .unwrap_or_else(|_| "unknown-host".to_string())
}

fn detect_user() -> String {
    env::var("USER")
        .or_else(|_| env::var("USERNAME"))
        .unwrap_or_else(|_| "unknown-user".to_string())
}

fn home_dir() -> Option<PathBuf> {
    env::var_os("HOME").map(PathBuf::from)
}

fn build_matcher(patterns: &[&str]) -> Result<GlobSet> {
    let mut builder = GlobSetBuilder::new();
    for pattern in patterns {
        builder.add(Glob::new(pattern).with_context(|| format!("invalid glob pattern: {pattern}"))?);
    }
    Ok(builder.build()?)
}

fn classify_version(profile: &IncidentProfile, version: &str) -> VersionHitStatus {
    if profile.bad_versions.iter().any(|bad| bad == &version) {
        VersionHitStatus::Compromised
    } else if profile.safe_version == version {
        VersionHitStatus::Safe
    } else {
        VersionHitStatus::Other
    }
}

fn push_limited(items: &mut Vec<String>, value: String) {
    if items.len() >= MAX_RECORDED_LIMITATION_ITEMS || items.contains(&value) {
        return;
    }
    items.push(value);
}

fn dedupe_paths(paths: &[PathBuf]) -> Vec<PathBuf> {
    let mut seen = BTreeSet::new();
    let mut deduped = Vec::new();
    for path in paths {
        let display = path.display().to_string();
        if seen.insert(display) {
            deduped.push(path.clone());
        }
    }
    deduped
}

fn classify_cache_source(path: &Path) -> String {
    let display = path.display().to_string();
    if display.contains(".cache/pip") {
        "pip_cache".to_string()
    } else if display.contains(".cache/uv") {
        "uv_cache".to_string()
    } else {
        "user_path".to_string()
    }
}

fn should_skip_scan_entry(entry: &DirEntry) -> bool {
    if !entry.file_type().is_dir() {
        return false;
    }

    matches!(
        entry.file_name().to_string_lossy().as_ref(),
        ".git" | "target" | "bundled"
    )
}

fn key_evidence_lines(report: &ScanReport, verbose: bool) -> Vec<String> {
    let mut lines = Vec::new();

    for hit in report
        .findings
        .version_hits
        .iter()
        .filter(|hit| matches!(hit.status, VersionHitStatus::Compromised))
        .take(5)
    {
        lines.push(format!(
            "Found compromised version {} in {}:{}",
            hit.version, hit.path, hit.line_number
        ));
    }

    for finding in report.findings.environment_hits.iter().filter(|f| f.bad_version).take(5) {
        if let Some(version) = &finding.version {
            lines.push(format!(
                "Environment check `{}` found compromised version {}",
                finding.check, version
            ));
        }
    }

    for hit in report.findings.ioc_file_hits.iter().take(5) {
        lines.push(format!("Found IOC file {} at {}", hit.indicator, hit.path));
    }

    for hit in report.findings.ioc_domain_hits.iter().take(5) {
        lines.push(format!(
            "Found IOC domain {} in {}:{}",
            hit.indicator,
            hit.path,
            hit.line_number.unwrap_or(0)
        ));
    }

    if lines.is_empty() && !report.findings.manifest_hits.is_empty() {
        for hit in report.findings.manifest_hits.iter().take(if verbose { 10 } else { 5 }) {
            lines.push(format!(
                "Found package reference in {}:{}",
                hit.path, hit.line_number
            ));
        }
    }

    lines
}

fn stderr_or_fallback(stderr: &str, fallback: &str) -> String {
    if stderr.trim().is_empty() {
        fallback.to_string()
    } else {
        stderr.trim().to_string()
    }
}

fn excerpt(value: &str, max_chars: usize) -> String {
    value.chars().take(max_chars).collect()
}

fn missing_llm_config_error() -> anyhow::Error {
    anyhow!(
        "AI explanation is not available because no LLM API key was found. Set SCIRA_LLM_API_KEY to enable explanation. scira will try to detect the provider and choose a default model automatically. If auto-detection does not work, also set SCIRA_LLM_PROVIDER."
    )
}

fn exit_code_for_status(status: IncidentStatus) -> i32 {
    match status {
        IncidentStatus::NoIndicatorsFound => 0,
        IncidentStatus::ReferencesFoundFollowUpNeeded => 10,
        IncidentStatus::LikelyAffected => 20,
    }
}

impl IncidentStatus {
    fn as_str(&self) -> &'static str {
        match self {
            IncidentStatus::NoIndicatorsFound => "no_indicators_found",
            IncidentStatus::ReferencesFoundFollowUpNeeded => "references_found_follow_up_needed",
            IncidentStatus::LikelyAffected => "likely_affected",
        }
    }
}

impl LlmProvider {
    fn as_str(&self) -> &'static str {
        match self {
            LlmProvider::Anthropic => "anthropic",
            LlmProvider::Openai => "openai",
            LlmProvider::Gemini => "gemini",
        }
    }
}

fn expand_tilde(path: PathBuf) -> PathBuf {
    let raw = path.to_string_lossy();
    if raw == "~" {
        if let Some(home) = home_dir() {
            return home;
        }
    }
    if let Some(rest) = raw.strip_prefix("~/") {
        if let Some(home) = home_dir() {
            return home.join(rest);
        }
    }
    path
}
